2023-06-20 17:00:31 | 
Traceback (most recent call last):
  File "C:\Users\Саша Бордо\PycharmProjects\pythonProject\oop1-7\test_Employee.py", line 68, in validate
    raise EmailAlreadyExistsException
test_Employee.EmailAlreadyExistsException
2023-06-20 17:01:13 | 
Traceback (most recent call last):
  File "C:\Users\Саша Бордо\PycharmProjects\pythonProject\oop1-7\test_Employee.py", line 68, in validate
    raise EmailAlreadyExistsException
test_Employee.EmailAlreadyExistsException
